displayName=Decimal Prices
author=rmaes4
description=Allows the use of decimals when typing a custom price. E.g. 2.5k = 2500
tags=ge,grandexchange,buy,sell,price,decimal
plugins=com.decimalprices.DecimalPrices
build=standard
